# docker-compose.yml
version: "3"

services:
  server:
    image: node:12
    working_dir: /{proyect-name}
    volumes:
      - ./:/{proyect-name}
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command: sh -c "npm install && npm run dev"
